<?php

namespace Database\Seeders;

use App\Models\Resume;
use Illuminate\Database\Seeder;

class ResumeSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Resume::query()->updateOrCreate(
            ['slug' => 'wolney-cesar-carneiro-eng-v1'],
            [
                'language' => 'eng',
                'version' => 'v1',
                'full_name' => 'Wolney Cesar Carneiro',
                'professional_title' => 'Senior Software Developer | Backend (PHP / Laravel)',
                'email' => 'wolney.dev@gmail.com',
                'phone' => null,
                'location' => 'São Paulo, SP, Brazil',
                'summary' => 'Senior Software Developer with 10 years of experience building, modernizing, and operating enterprise and government systems, focused on backend engineering with PHP and Laravel. Strong background in RESTful API design, software architecture, relational databases including PostgreSQL, MySQL, and SQL Server, and CI/CD automation with GitLab CI, GitHub Actions, and Argo CD. Former Software Architect who defined architecture and development standards and provided technical leadership across multiple projects. Hands-on experience with Docker, PHPUnit automated testing, legacy system modernization, and AI-assisted development using Cursor. Fluent in English.',
                'linkedin_url' => 'https://linkedin.com/in/wolney-carneiro-10w',
                'github_url' => 'https://github.com/wolneydev',
                'portfolio_url' => null,
                'website_url' => null,
                'experiences' => [
                    [
                        'title' => 'Senior Software Developer',
                        'company' => 'Linuxell Informática',
                        'end_date' => '2026-04',
                        'location' => 'Brazil',
                        'highlights' => [
                            'Maintained and evolved a large-scale government system serving Brazilian citizens, built with PHP, Laravel, Angular, PostgreSQL, and SQL Server.',
                            'Implemented architectural improvements and delivered new features, improving system maintainability and reducing defects and incidents.',
                            'Automated build, test, and deployment workflows with GitLab CI/CD and Argo CD, supporting frequent production deployments.',
                            'Wrote and maintained PHPUnit unit tests to prevent regressions and ensure application reliability.',
                            'Collaborated with engineering teams to improve delivery workflows, code standards, and maintainability.',
                        ],
                        'is_current' => false,
                        'start_date' => '2024-04',
                        'description' => 'Developed, maintained, and modernized a large-scale government platform using PHP, Laravel, Angular, PostgreSQL, SQL Server, MySQL, JavaScript, REST APIs, GitLab CI/CD, Argo CD, PHPUnit, Docker, Scrum, and Kanban.',
                    ],
                    [
                        'title' => 'Software Architect',
                        'company' => 'Avansys Tecnologia',
                        'end_date' => '2024-04',
                        'location' => 'Brazil',
                        'highlights' => [
                            'Defined software architecture and development standards adopted across two major projects, providing technical leadership to four engineers.',
                            'Built reusable Laravel scaffolds that standardized project structure, automated application layers, accelerated development, and reduced release time by six months.',
                            'Designed and maintained GitLab CI pipelines to automate build, testing, and deployment for four major applications.',
                            'Developed SPA-based financial systems with Vue.js frontends and Laravel REST APIs and supported legacy platform modernization initiatives.',
                            'Prototyped asynchronous service-to-service messaging with RabbitMQ, evaluating decoupling patterns for distributed architectures.',
                            'Integrated enterprise systems through RESTful APIs and maintained API documentation with Swagger and OpenAPI.',
                            'Performed code reviews and resolved production issues, ensuring technical quality across teams.',
                        ],
                        'is_current' => false,
                        'start_date' => '2019-09',
                        'description' => 'Led architecture and backend development initiatives using PHP, Laravel, Vue.js, PostgreSQL, SQL Server, MySQL, JavaScript, REST APIs, GitLab CI, RabbitMQ, Swagger, Docker, Scrum, and Kanban.',
                    ],
                    [
                        'title' => 'Systems Analyst',
                        'company' => 'Companhia de Governança Eletrônica de Salvador',
                        'end_date' => '2019-09',
                        'location' => 'Salvador, BA, Brazil',
                        'highlights' => [
                            'Developed and maintained web systems for public sector institutions using PHP, JavaScript, jQuery, and Bootstrap.',
                            'Delivered contract management and service desk systems used by two agencies.',
                            'Integrated frontend applications with REST APIs and web services and maintained and migrated legacy systems.',
                            'Optimized SQL queries on MySQL and SQL Server, improving web application performance.',
                        ],
                        'is_current' => false,
                        'start_date' => '2016-07',
                        'description' => 'Worked through contracted service providers developing public-sector systems with PHP, JavaScript, jQuery, jQuery Mobile, Bootstrap, Apache, Cordova, REST APIs, Web Services, MySQL, and SQL Server.',
                    ],
                ],
                'education' => [
                    [
                        'field' => 'Information Systems',
                        'degree' => "Bachelor's Degree",
                        'end_date' => null,
                        'start_date' => null,
                        'description' => null,
                        'institution' => 'Faculdade Dom Pedro II',
                    ],
                    [
                        'field' => 'Project Management',
                        'degree' => 'Postgraduate Certificate',
                        'end_date' => null,
                        'start_date' => null,
                        'description' => null,
                        'institution' => 'Wyden',
                    ],
                ],
                'skills' => [
                    ['name' => 'PHP', 'level' => 'advanced'],
                    ['name' => 'Laravel', 'level' => 'advanced'],
                    ['name' => 'RESTful APIs', 'level' => 'advanced'],
                    ['name' => 'Software Architecture', 'level' => 'advanced'],
                    ['name' => 'SOLID Principles', 'level' => 'advanced'],
                    ['name' => 'Legacy System Modernization', 'level' => 'advanced'],
                    ['name' => 'PostgreSQL', 'level' => 'advanced'],
                    ['name' => 'MySQL', 'level' => 'advanced'],
                    ['name' => 'SQL Server', 'level' => 'advanced'],
                    ['name' => 'SQL Query Optimization', 'level' => 'advanced'],
                    ['name' => 'Docker', 'level' => 'intermediate'],
                    ['name' => 'GitLab CI', 'level' => 'advanced'],
                    ['name' => 'GitHub Actions', 'level' => 'intermediate'],
                    ['name' => 'Argo CD', 'level' => 'intermediate'],
                    ['name' => 'CI/CD', 'level' => 'advanced'],
                    ['name' => 'PHPUnit', 'level' => 'advanced'],
                    ['name' => 'Swagger / OpenAPI', 'level' => 'intermediate'],
                    ['name' => 'RabbitMQ', 'level' => 'intermediate'],
                    ['name' => 'JavaScript', 'level' => 'intermediate'],
                    ['name' => 'Angular', 'level' => 'intermediate'],
                    ['name' => 'Vue.js', 'level' => 'intermediate'],
                    ['name' => 'Bootstrap', 'level' => 'intermediate'],
                    ['name' => 'Cursor', 'level' => 'advanced'],
                    ['name' => 'Prompt Engineering', 'level' => 'intermediate'],
                    ['name' => 'Scrum', 'level' => 'advanced'],
                    ['name' => 'Kanban', 'level' => 'advanced'],
                ],
                'certifications' => [
                    [
                        'url' => null,
                        'date' => '2024-09',
                        'name' => 'Certified Scrum Developer® (CSD)',
                        'issuer' => 'Scrum Alliance',
                    ],
                    [
                        'url' => null,
                        'date' => '2023',
                        'name' => 'Hexagonal Architecture, Event Storming, RabbitMQ, Docker, Software Architecture Fundamentals, and SOLID',
                        'issuer' => 'Full Cycle',
                    ],
                    [
                        'url' => null,
                        'date' => '2023',
                        'name' => 'Laravel Microservices API Gateway and RabbitMQ',
                        'issuer' => 'EspecializaTI',
                    ],
                    [
                        'url' => null,
                        'date' => null,
                        'name' => 'Docker and Kubernetes: The Complete Guide',
                        'issuer' => 'Udemy',
                    ],
                    [
                        'url' => null,
                        'date' => null,
                        'name' => 'Complete React Course',
                        'issuer' => 'Udemy',
                    ],
                    [
                        'url' => null,
                        'date' => null,
                        'name' => 'Building RESTful APIs with Laravel',
                        'issuer' => 'Udemy',
                    ],
                    [
                        'url' => null,
                        'date' => null,
                        'name' => 'Java Web with JSF, PrimeFaces, and JPA',
                        'issuer' => 'Softblue',
                    ],
                ],
                'projects' => [],
                'spoken_languages' => [
                    ['name' => 'Portuguese', 'level' => 'native'],
                    ['name' => 'English', 'level' => 'fluent'],
                ],
                'is_published' => true,
            ]
        );

        Resume::query()->updateOrCreate(
            ['slug' => 'wolney-cesar-carneiro-por-v1'],
            [
                'language' => 'por',
                'version' => 'v1',
                'full_name' => 'Wolney Cesar Carneiro',
                'professional_title' => 'Desenvolvedor de Software Sênior | Backend (PHP / Laravel)',
                'email' => 'wolney.dev@gmail.com',
                'phone' => null,
                'location' => 'São Paulo, SP, Brasil',
                'summary' => 'Desenvolvedor de Software Sênior com 10 anos de experiência no desenvolvimento, modernização e sustentação de sistemas corporativos e governamentais, com foco em backend utilizando PHP e Laravel. Sólida experiência em APIs REST, arquitetura de software, bancos de dados relacionais (PostgreSQL, MySQL e SQL Server) e automação de CI/CD com GitLab CI, GitHub Actions e Argo CD. Atuou como Arquiteto de Software definindo padrões arquiteturais e liderando tecnicamente múltiplos projetos. Experiência prática com Docker, testes automatizados utilizando PHPUnit, modernização de sistemas legados e desenvolvimento assistido por IA com Cursor. Inglês fluente.',
                'linkedin_url' => 'https://linkedin.com/in/wolney-carneiro-10w',
                'github_url' => 'https://github.com/wolneydev',
                'portfolio_url' => null,
                'website_url' => null,
                'experiences' => [
                    [
                        'title' => 'Desenvolvedor de Software Sênior',
                        'company' => 'Linuxell Informática',
                        'start_date' => '2024-04',
                        'end_date' => '2026-04',
                        'is_current' => false,
                        'location' => 'Brasil',
                        'description' => 'Atuação na evolução e sustentação de um sistema governamental de grande porte utilizando PHP, Laravel, Angular, PostgreSQL, SQL Server, Docker, GitLab CI/CD e Argo CD.',
                        'highlights' => [
                            'Evoluiu um sistema governamental de grande escala utilizado por cidadãos brasileiros.',
                            'Implementou melhorias arquiteturais reduzindo incidentes e aumentando a manutenibilidade.',
                            'Automatizou pipelines de build, testes e deploy com GitLab CI/CD e Argo CD.',
                            'Desenvolveu testes unitários com PHPUnit para reduzir regressões.',
                            'Colaborou na definição de padrões de desenvolvimento e melhoria dos processos de entrega.',
                        ],
                    ],
                    [
                        'title' => 'Arquiteto de Software',
                        'company' => 'Avansys Tecnologia',
                        'start_date' => '2019-09',
                        'end_date' => '2024-04',
                        'is_current' => false,
                        'location' => 'Brasil',
                        'description' => 'Definição de arquitetura, liderança técnica e desenvolvimento de soluções Laravel e Vue.js para sistemas corporativos.',
                        'highlights' => [
                            'Definiu padrões arquiteturais adotados em dois grandes projetos.',
                            'Criou scaffolds reutilizáveis em Laravel reduzindo o tempo de entrega em seis meses.',
                            'Automatizou pipelines GitLab CI para build, testes e deploy.',
                            'Desenvolveu sistemas financeiros SPA com Vue.js e APIs REST em Laravel.',
                            'Implementou provas de conceito com RabbitMQ para comunicação assíncrona.',
                            'Realizou integrações via APIs REST e documentação Swagger/OpenAPI.',
                            'Executou code reviews e suporte a produção.',
                        ],
                    ],
                    [
                        'title' => 'Analista de Sistemas',
                        'company' => 'Companhia de Governança Eletrônica de Salvador',
                        'start_date' => '2016-07',
                        'end_date' => '2019-09',
                        'is_current' => false,
                        'location' => 'Salvador, BA, Brasil',
                        'description' => 'Desenvolvimento de sistemas para órgãos públicos utilizando PHP, JavaScript e bancos relacionais.',
                        'highlights' => [
                            'Desenvolveu sistemas web para instituições públicas.',
                            'Entregou sistemas de gestão de contratos e service desk.',
                            'Realizou integrações com APIs REST e Web Services.',
                            'Otimizou consultas SQL em MySQL e SQL Server.',
                        ],
                    ],
                ],
                'education' => [
                    [
                        'institution' => 'Faculdade Dom Pedro II',
                        'degree' => 'Bacharelado',
                        'field' => 'Sistemas de Informação',
                        'start_date' => null,
                        'end_date' => null,
                        'description' => null,
                    ],
                    [
                        'institution' => 'Wyden',
                        'degree' => 'Pós-graduação',
                        'field' => 'Gerenciamento de Projetos',
                        'start_date' => null,
                        'end_date' => null,
                        'description' => null,
                    ],
                ],
                'skills' => [
                    ['name' => 'PHP', 'level' => 'avançado'],
                    ['name' => 'Laravel', 'level' => 'avançado'],
                    ['name' => 'APIs REST', 'level' => 'avançado'],
                    ['name' => 'Arquitetura de Software', 'level' => 'avançado'],
                    ['name' => 'PostgreSQL', 'level' => 'avançado'],
                    ['name' => 'MySQL', 'level' => 'avançado'],
                    ['name' => 'SQL Server', 'level' => 'avançado'],
                    ['name' => 'Docker', 'level' => 'intermediário'],
                    ['name' => 'GitLab CI', 'level' => 'avançado'],
                    ['name' => 'GitHub Actions', 'level' => 'intermediário'],
                    ['name' => 'Argo CD', 'level' => 'intermediário'],
                    ['name' => 'PHPUnit', 'level' => 'avançado'],
                    ['name' => 'RabbitMQ', 'level' => 'intermediário'],
                    ['name' => 'Angular', 'level' => 'intermediário'],
                    ['name' => 'Vue.js', 'level' => 'intermediário'],
                    ['name' => 'JavaScript', 'level' => 'intermediário'],
                    ['name' => 'Cursor', 'level' => 'avançado'],
                    ['name' => 'Scrum', 'level' => 'avançado'],
                    ['name' => 'Kanban', 'level' => 'avançado'],
                ],
                'certifications' => [
                    [
                        'name' => 'Certified Scrum Developer® (CSD)',
                        'issuer' => 'Scrum Alliance',
                        'date' => '2024-09',
                        'url' => null,
                    ],
                    [
                        'name' => 'Arquitetura Hexagonal, Event Storming, RabbitMQ, Docker, Fundamentos de Arquitetura de Software e SOLID',
                        'issuer' => 'Full Cycle',
                        'date' => '2023',
                        'url' => null,
                    ],
                    [
                        'name' => 'Laravel Microservices API Gateway and RabbitMQ',
                        'issuer' => 'EspecializaTI',
                        'date' => '2023',
                        'url' => null,
                    ],
                ],
                'projects' => [],
                'spoken_languages' => [
                    ['name' => 'Português', 'level' => 'nativo'],
                    ['name' => 'Inglês', 'level' => 'fluente'],
                ],
                'is_published' => true,
            ]
        );
    }
}
